name: push-docs

on:
  push:
    branches:
      - main
    # paths:
      # - documentation/docs/**

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: huhn511/iota-wiki
          path: iota-wiki
      - name: Copy docs
        run: |
          echo "Print dir content"
          ls
          git clone https://github.com/${{ github.repository }} --single-branch --branch main
          ls
          rm iota-wiki/README.md
          cp remote-pr-test/README.md iota-wiki/README.md
          ls 
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: iota-wiki
          commit-message: Update ${{ github.repository }} docs
          branch: docs/update-${{ github.repository }}
          delete-branch: true
          title: Update docs